name: 'prepare'
description: "An action to prepare the environement."
author: 'lchenay'
branding:
  icon: 'anchor'
  color: 'blue'

runs:
  using: "composite"
  steps:
    - name: Git - Fetch tags
      shell: bash
      run: echo "A lot of installation ; preparation"

    - uses: ./.github/actions/complex-cache
      name: "Complex cache"
      with: 
        dir: 'build'
